name: x86_64 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-all-rpm:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:9
      options: --cpus 4
    steps:
    - uses: actions/checkout@v4
      with:
        path: fuse-kernel-modules
    - name: Create tar ball
      run: |
        source fuse-kernel-modules/src/dkms.conf
        cp -rf fuse-kernel-modules fuse-kernel-modules-${PACKAGE_VERSION}
        mkdir -p rpmbuild/SOURCES rpmbuild/SPECS
        tar zcvf rpmbuild/SOURCES/v${PACKAGE_VERSION}.tar.gz fuse-kernel-modules-${PACKAGE_VERSION}
        cp fuse-kernel-modules/redhat/*.spec rpmbuild/SPECS
    - name: Install tools and Libraries
      run: |
        dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm -y
        dnf install https://download.rockylinux.org/vault/rocky/9.5/AppStream/x86_64/os/Packages/k/kernel-devel-5.14.0-503.40.1.el9_5.x86_64.rpm -y
        dnf install https://download.rockylinux.org/vault/rocky/9.6/AppStream/x86_64/os/Packages/k/kernel-devel-5.14.0-570.26.1.el9_6.x86_64.rpm -y
        dnf install rpm-build kmodtool gnupg2 rpm-sign -y
    - name: Import GPG keys
      run: |
        gpg --import << EOF
        ${{ secrets.GPG_PRIVATE_KEY }}
        EOF
    - name: Build the RPMS
      run: |
        source fuse-kernel-modules/src/dkms.conf
        rpmbuild -ba --define "_topdir $PWD/rpmbuild" --define "fuse_version $PACKAGE_VERSION" \
                 rpmbuild/SPECS/fuse-dkms.spec
        rpmbuild -ba --define "_topdir $PWD/rpmbuild" rpmbuild/SPECS/fuse-kernel-modules.spec
        rpmbuild -bb --define "_topdir $PWD/rpmbuild" rpmbuild/SPECS/fuse-kmod.spec
        rpmbuild -ba --define "kernels 5.14.0-570.26.1.el9_6.x86_64 5.14.0-503.40.1.el9_5.x86_64" \
                     --define "_topdir $PWD/rpmbuild" rpmbuild/SPECS/fuse-kmod.spec
        find rpmbuild/RPMS/ -name '*.rpm' | xargs rpmsign --define "_gpg_name F96A409277704327" \
                     --define "_gpg_sign_cmd_extra_args --batch" --addsign

